let course = [
  {
    image: "./course-img/react.png",
    title: "Learn React : React Complete Course for Beginners",
    courseUpdated: "09/12/22",
    starts: 5,
    reviews: 550,
    price: 250,
    subject: "Programming",
  },
  {
    image: "./course-img/aws.jpg",
    title: "Learn AWS : AWS Complete Course for Beginners",
    courseUpdated: "22/10/22",
    starts: 4,
    reviews: 392,
    price: 250,
    subject: "Programming",
  },
  {
    image: "./course-img/angular.png",
    title: "Angular Complete Course for Beginners",
    courseUpdated: "12/11/22",
    starts: 5,
    reviews: 202,
    price: 250,
    subject: "Programming",
  },
  {
    image: "./course-img/js.jpg",
    title: "Javascript Complete Course for Beginners",
    courseUpdated: "12/12/22",
    stars: 5,
    reviews: 422,
    price: "250",
    subject: "Programming",
  },
  {
    image: "./course-img/c++.jpg",
    title: "Learn C++ Complete Course for Beginners",
    courseUpdated: "21/08/22",
    stars: 4,
    reviews: 223,
    price: "250",
    subject: "Programming",
  },
  {
    image: "./course-img/python.jpg",
    title: "Python for Beginners Complete Course from scratch",
    courseUpdated: "02/10/22",
    stars: 4,
    reviews: 322,
    price: "250",
    subject: "Programming",
  },
  {
    image: "./course-img/java.png",
    title: "Learn Java Complete Course for Beginners",
    courseUpdated: "02/11/22",
    stars: 5,
    reviews: 622,
    price: "250",
    subject: "Programming",
  },
  {
    image: "./course-img/go.jpg",
    title: "GoLang : Complete Course for Beginners",
    courseUpdated: "22/11/22",
    stars: 4,
    reviews: 222,
    price: "250",
    subject: "Programming",
  },
  {
    image: "./course-img/csharp.png",
    title: "C#(.Net) Complete Course for Beginners",
    courseUpdated: "29/11/22",
    stars: 3,
    reviews: 322,
    price: "250",
    subject: "Programming",
  },
  {
    image: "./course-img/aws.jpg",
    title: "Amazon Web Service Complete Course for Beginners",
    courseUpdated: "20/10/22",
    stars: 5,
    reviews: 422,
    price: "250",
    subject: "Programming",
  },
  {
    image: "./course-img/ourcourseimg/graficdesign/KTsKk7aTNqEiKvGQVaCqF5.jpg",
    title: "Photoshop Complete Course for Beginners from Scratch",
    courseUpdated: "12/11/22",
    starts: 4,
    reviews: 392,
    price: 250,
    subject: "GraphicDesign",
  },
  {
    image: "./course-img/go.jpg",
    title: "Learn GoLang for Beginers Complete Course",
    courseUpdated: "12/11/22",
    starts: 5,
    reviews: 292,
    price: 250,
    subject: "Programming",
  },
  {
    image:
      "./course-img/ourcourseimg/graficdesign/adobe-illustrator-course_1_0.webp",
    title: "Javascript Complete Course for Beginners",
    courseUpdated: "12/11/22",
    starts: 5,
    reviews: 222,
    price: 250,
    subject: "GraphicDesign",
  },
  {
    image:
      "./course-img/ourcourseimg/graficdesign/adobe-illustrator-course_1_0.webp",
    title: "Adobe illustration Complete Course for Beginners",
    courseUpdated: "22/11/22",
    stars: 4,
    reviews: 450,
    price: 250,
    subject: "GraphicDesign",
  },
  {
    image:
      "./course-img/ourcourseimg/graficdesign/collection-financial-investment-bank-deposit-profit-finance-manage-money-cartoon-style-graphic-designer-vector-illustration_1150-65257.webp",
    title: "Learn Graphic design Complete Course for Beginners",
    courseUpdated: "29/11/22",
    stars: 5,
    reviews: 400,
    price: 250,
    subject: "GraphicDesign",
  },
  {
    image:
      "./course-img/ourcourseimg/graficdesign/cover-800x450-1-800x450-1.jpg",
    title: "Abobe Graphic design Complete Course for Beginners",
    courseUpdated: "21/11/22",
    stars: 4,
    reviews: 350,
    price: 250,
    subject: "GraphicDesign",
  },
  {
    image: "./course-img/ourcourseimg/graficdesign/download.png",
    title: "Learn designing Complete Course for Beginners",
    courseUpdated: "02/07/22",
    stars: 3,
    reviews: 300,
    price: 250,
    subject: "GraphicDesign",
  },
  {
    image:
      "./course-img/ourcourseimg/graficdesign/funny-young-man-sitting-desk-drawing-graphic-tablet-digital-designer-illustrator-freelancer-working-home-cute-guy-enjoying-his-hobby-flat-cartoon-colorful-vector-illustration_198278-8046.webp",
    title: "Learn Complete Graphic designing Course from Beginning",
    courseUpdated: "22/11/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "GraphicDesign",
  },
  {
    image: "./course-img/ourcourseimg/graficdesign/graphic-design-tools.avif",
    title: "Graphic design tools Complete Course for Beginners",
    courseUpdated: "23/11/22",
    stars: 5,
    reviews: 500,
    price: 250,
    subject: "GraphicDesign",
  },
  {
    image: "./course-img/ourcourseimg/graficdesign/InDesign-e1504864653231.jpg",
    title: "Learn Indesign Complete Course for Beginners",
    courseUpdated: "27/10/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "GraphicDesign",
  },
  {
    image: "./course-img/ourcourseimg/graficdesign/KTsKk7aTNqEiKvGQVaCqF5.jpg",
    title: "Learn : Photoshop Complete Course for Beginners",
    courseUpdated: "22/12/22",
    stars: 5,
    reviews: 450,
    price: 250,
    subject: "GraphicDesign",
  },
  {
    image:
      "./course-img/ourcourseimg/graficdesign/Package-Adobe-Graphics-Gold-1200x675.jpg",
    title:
      "Learn Indesign, Photoshop & illustrator Complete Course for Beginners",
    courseUpdated: "22/10/22",
    stars: 4,
    reviews: 350,
    price: 250,
    subject: "GraphicDesign",
  },
  {
    image: "./course-img/ourcourseimg/Music/attending-guitar-class.jpg",
    title: "Guitter Complete Course for Beginners",
    courseUpdated: "21/01/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Music",
  },
  {
    image:
      "./course-img/ourcourseimg/Music/colorful-indian-tabla-music-notes-260nw-597921116.webp",
    title: "Thabala Complete Course",
    courseUpdated: "02/08/21",
    stars: 3,
    reviews: 350,
    price: 250,
    subject: "Music",
  },
  {
    image: "./course-img/ourcourseimg/Music/download.jfif",
    title: "Piano Advance Course",
    courseUpdated: "21/04/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Music",
  },
  {
    image: "./course-img/ourcourseimg/Music/flute-course-500x500.webp",
    title: "Flute Complete Course for Beginners",
    courseUpdated: "22/01/22",
    stars: 5,
    reviews: 450,
    price: 250,
    subject: "Music",
  },
  {
    image: "./course-img/ourcourseimg/Music/images.jfif",
    title: "Basic Music Instrument course",
    courseUpdated: "22/01/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Music",
  },
  {
    image: "./course-img/ourcourseimg/Music/music1.png",
    title: "Online Music learning tutorial for children",
    courseUpdated: "22/09/21",
    stars: 5,
    reviews: 500,
    price: 250,
    subject: "Music",
  },
  {
    image:
      "./course-img/ourcourseimg/Music/colorful-indian-tabla-music-notes-260nw-597921116.webp",
    title: "Thabala Advance Course",
    courseUpdated: "22/11/20",
    stars: 3,
    reviews: 300,
    price: 250,
    subject: "Music",
  },
  {
    image: "./course-img/ourcourseimg/Music/download.jfif",
    title: "Piano Advance Course",
    courseUpdated: "12/11/19",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Music",
  },
  {
    image:
      "./course-img/ourcourseimg/Bussiness/GettyImages-1153397912-5cc5918639d6482b8b1b035413b8c267.jpg",
    title: "Digital Marketing Complete Course for Beginners",
    courseUpdated: "12/11/22",
    starts: 4,
    reviews: 392,
    price: 250,
    subject: "Bussines",
  },
  {
    image: "./course-img/ourcourseimg/graficdesign/KTsKk7aTNqEiKvGQVaCqF5.jpg",
    title: "Digital Marketing Complete Course for Beginners",
    courseUpdated: "02/09/22",
    starts: 4,
    reviews: 310,
    price: 250,
    subject: "Bussines",
  },
  {
    image: "./course-img/ourcourseimg/maths/1_L76A5gL6176UbMgn7q4Ybg.jpeg",
    title: "Basic Maths Complete Course for Beginners",
    courseUpdated: "22/11/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Mathematics",
  },
  {
    image: "./course-img/ourcourseimg/maths/integration-1364673_960_720.jpg",
    title: "Integration Complete Course for Beginners",
    courseUpdated: "21/11/22",
    stars: 5,
    reviews: 450,
    price: 250,
    subject: "Mathematics",
  },
  {
    image: "./course-img/ourcourseimg/maths/iStock_000020584512XSmall.jpg",
    title: "Geometry Complete Course for Beginners",
    courseUpdated: "02/02/22",
    stars: 4,
    reviews: 350,
    price: 250,
    subject: "Mathematics",
  },
  {
    image: "./course-img/ourcourseimg/maths/learn_algebra.jpg",
    title: "Algebra Course for Beginners",
    courseUpdated: "02/10/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Mathematics",
  },
  {
    image:
      "./course-img/ourcourseimg/maths/mathematics-math-algebra-calculus-numbers-260nw-521153674.webp",
    title: "Algebra Advance Course for Beginners",
    courseUpdated: "29/11/22",
    stars: 3,
    reviews: 300,
    price: 250,
    subject: "Mathematics",
  },
  {
    image: "./course-img/ourcourseimg/maths/mathematics-png.jpg",
    title: "Advance Maths Complete Course for Beginners",
    courseUpdated: "22/09/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Mathematics",
  },
  {
    image: "./course-img/ourcourseimg/maths/maxresdefault.jpg",
    title: "Integration & Differentiation Complete Course for Beginners",
    courseUpdated: "02/02/22",
    stars: 5,
    reviews: 500,
    price: 250,
    subject: "Mathematics",
  },
  {
    image: "./course-img/ourcourseimg/maths/integration-1364673_960_720.jpg",
    title: "Learn Integration Advance Course to be Expert",
    courseUpdated: "09/11/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Mathematics",
  },
  {
    image: "./course-img/ourcourseimg/maths/1_L76A5gL6176UbMgn7q4Ybg.jpeg",
    title: "Maths Complete Course for Beginners",
    courseUpdated: "22/11/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Mathematics",
  },
  {
    image: "./course-img/ourcourseimg/Bussiness/960x0.jpg",
    title: "Business Management Complete Course for Beginners",
    courseUpdated: "22/11/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Business",
  },
  {
    image: "./course-img/ourcourseimg/Bussiness/B2B-B2C-1920w.webp",
    title: "How B2B & B2C works Complete Course for Beginners",
    courseUpdated: "12/11/22",
    stars: 5,
    reviews: 450,
    price: 250,
    subject: "Business",
  },
  {
    image:
      "./course-img/ourcourseimg/Bussiness/best-b2b-business-marketing-course-class-certification-training-online.jpg",
    title: "Business Ideas Course to start Business",
    courseUpdated: "22/10/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Business",
  },
  {
    image:
      "./course-img/ourcourseimg/Bussiness/best-business-analysis-course-class-certification-degree-training-online.jpg",
    title: "Online Business Complete Course for Businessmen",
    courseUpdated: "12/11/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Business",
  },
  {
    image: "./course-img/ourcourseimg/Bussiness/download(1).jfif",
    title: "Marketing Complete Course for Beginners",
    courseUpdated: "03/11/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Business",
  },
  {
    image: "./course-img/ourcourseimg/Bussiness/download.png",
    title: "Linkedin Marketing Complete Course for Beginners",
    courseUpdated: "22/01/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Business",
  },
  {
    image:
      "./course-img/ourcourseimg/Bussiness/GettyImages-1153397912-5cc5918639d6482b8b1b035413b8c267.jpg",
    title: "Digital Marketing Complete Course for Beginners",
    courseUpdated: "02/01/22",
    stars: 5,
    reviews: 500,
    price: 250,
    subject: "Business",
  },
  {
    image: "./course-img/ourcourseimg/Bussiness/logo2.png",
    title: "Management Complete Course for Beginners",
    courseUpdated: "12/11/21",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Business",
  },
  {
    image: "./course-img/ourcourseimg/science/1538985491phpKctLgx.jpeg",
    title: "Learn Biology Basic Course for Students",
    courseUpdated: "21/10/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Science",
  },
  {
    image: "./course-img/ourcourseimg/science/DCS.png",
    title: "Digital Electronics Complete Course for Beginners",
    courseUpdated: "22/01/22",
    stars: 5,
    reviews: 450,
    price: 250,
    subject: "Science",
  },
  {
    image:
      "./course-img/ourcourseimg/science/Class-10-Arithmetic-Progression.jpg",
    title: "Learn Basic Maths Course for Beginners",
    courseUpdated: "23/11/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Science",
  },
  {
    image: "./course-img/ourcourseimg/science/chemistry_logo.png",
    title: "Learn Basic Chemistry Course for Beginners",
    courseUpdated: "09/11/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Science",
  },
  {
    image: "./course-img/ourcourseimg/science/basic-electonics.jpg",
    title: "Learn Basic Electronics Course for Beginners",
    courseUpdated: "12/10/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Science",
  },
  {
    image: "./course-img/ourcourseimg/science/digitalamatte.png",
    title: "Advance Maths Complete Course for Experts",
    courseUpdated: "21/11/22",
    stars: 5,
    reviews: 500,
    price: 250,
    subject: "Science",
  },
  {
    image: "./course-img/ourcourseimg/science/download.jfif",
    title: "Analog Electronics Complete Course for Beginners",
    courseUpdated: "12/11/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Science",
  },
  {
    image: "./course-img/ourcourseimg/science/file-20171025-25516-g7rtyl.avif",
    title: "Physics Complete Course for Beginners",
    courseUpdated: "22/11/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Science",
  },
  {
    image: "./course-img/ourcourseimg/science/GeoDisciplinesDiagram338x266.jpg",
    title: "Geology Complete Course for Beginners",
    courseUpdated: "22/11/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Science",
  },
  {
    image: "./course-img/ourcourseimg/science/myhc_89683.jpg",
    title: "Digital Electronics Complete Course for Beginners",
    courseUpdated: "23/11/22",
    stars: 4,
    reviews: 400,
    price: 250,
    subject: "Science",
  },
];

export default course;
